### ISSUE TITLE
Add commit standard checks for Pull Requests

### ISSUE THREAD

**Issue by alextilot** [amelioro/ameliorate#127]
**Is your feature request related to a problem? Please describe.**
As a developer I want commit history to be checked on pull requests to keep the conventional commit standardized. 

**Describe the solution you'd like**
Using Github Actions, check the commits and verify they are valid during a Pull Request.

**Describe alternatives you've considered**
Allowing users to self govern their commits

**Additional context**
[About status checks
](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/collaborating-on-repositories-with-code-quality-features/about-status-checks)

[Creating CI tests with the Checks API](https://docs.github.com/en/apps/creating-github-apps/guides/creating-ci-tests-with-the-checks-api)

**Technical ideas**

**Comment by keyserj** [comment]
Checks API may be useful but might not need to go too deep into that. It's worth investigating if an existing action is out there first (quick google shows https://github.com/webiny/action-conventional-commits might work)

Also note that we do already have one github action [ci.yml](https://github.com/amelioro/ameliorate/blob/main/.github/workflows/ci.yml) to run linting on pull requests, so that may be helpful for reference

**Comment by keyserj** [comment]
forgot to mention, it'll probably be most useful to look at the [GitHub Actions docs](https://docs.github.com/en/actions/learn-github-actions/understanding-github-actions)
