### ISSUE TITLE
Node text is not focused when adding through diagram

### ISSUE THREAD

**Issue by alextilot** [amelioro/ameliorate#57]
There is a bug where a node that is in the react-flow diagram looses focus after initial mounting. 
This is unexpected behavior.

https://github.com/amelioro/ameliorate/assets/13872370/693175a8-1903-4079-9db7-b34ff913614a

**Comment by keyserj** [comment]
I tried moving the addNode event outside of `setState` so that state changes would be done before the event is triggered, and therefore the new node could call focus() after all renders are done, but realized that react responds to state change asynchronously (I think for the purpose of batching multiple state changes). Tried using [flushSync](https://beta.reactjs.org/reference/react-dom/flushSync) (though even if that worked I'm not sure we'd want to use it) and it still didn't work! It seems that there are still some flow re-renders occurring afterwards:
![image](https://user-images.githubusercontent.com/13872370/222197761-bb9f4c6f-aaae-48e6-bbf2-74ec927eaa07.png)

**Comment by keyserj** [comment]
Another idea I've got is that react-flow tracks a `selected` state for the node that's selected (for when it's clicked on) - we might be able to take advantage of that to focus when a node is selected

**Comment by keyserj** [comment]
Another note - focusing on render is actually pretty awkward for mobile, because every time mobile loads the page, the keyboard pops up
